### ISSUE TITLE
Connect to node issues 

### ISSUE THREAD

**Issue by Q8w3rgxr** [arcbtc/M5StackSats#15]
Is there a way of telling why it cant connect to a node (raspiblitz)? I double checked the (local) ip adress and the ssl certificate but the only feedback i get is "no node detected". Any ideas how i can check whats missing or wrong? 

Thanks in advance!

**Comment by openoms** [comment]
Hi, trying to set up with my Blitz too and wondering the same.
```
String readmacaroon = "YOUR-LND-READ-MACAROON";
String invoicemacaroon = "YOUR-LND-INVOICE-MACAROON";
```
I presumed these need the HEX export of the macaroons.

Also have reset the TLS certificate to no success. (Can do that from the RaspiBlitz EXPORT menu)

Trying to set up on my LAN currently, but can't get past the flashing:
`NO NODE DETECTED`

**Comment by Q8w3rgxr** [comment]
I am also using the HEX macaroons, but this shouldnt affect the node connection nodecheck right? 

As you mentioned LAN, first time testing i tried with an 5Ghz network but the M5Stack only supports 2,4Ghz (produces the same "no node detected" error).

**Comment by openoms** [comment]
Yes, can confirm, I am connecting to a 2.4 Ghz WiFi too. The network has access to the node if connecting with any other device.

**Comment by arcbtc** [comment]
Not connected directly over LAN, so you can hit in a browser https://YOUR-NODE-IP:8080/v1/getinfo ?

**Comment by arcbtc** [comment]
Maybe try doing it without the cert 
comment out all the occurrences of 
`client.setCACert(test_root_ca);` 
to 
`//client.setCACert(test_root_ca);`

**Comment by arcbtc** [comment]
Or just comment out the cert in node check, that will clarify whether you need to use the cert

    void nodecheck(){
      bool checker = false;
      while(!checker){
      WiFiClientSecure client;
      //client.setCACert(test_root_ca);
      if (!client.connect(server, lndport)){
        M5.Lcd.fillScreen(BLACK);
         M5.Lcd.setCursor(20, 80);
         M5.Lcd.setTextSize(3);
         M5.Lcd.setTextColor(TFT_RED);
         M5.Lcd.println("NO NODE DETECTED");
         delay(1000);
      }
      else{
        checker = true;
      }
      }
    }

**Comment by arcbtc** [comment]
Lol, it seems I have connected over LAN before:
https://github.com/arcbtc/M5StackSats/issues/13

**Comment by openoms** [comment]
> Lol, it seems I have connected over LAN before:
> #13 

Great, thanks! These mods have sorted the connection through LAN and through a Dynamic DNS (with the port 8080 forwarded) too.
Seems the problem was the TLS certificate.
Does this mean that now the communication is in cleartext through the internet?

**Comment by arcbtc** [comment]
Nice, so your M5StackSats is fully operational?
I assume you're still encrypting, its just wificlientsecure is trusting the certificate. 
I'll investigate further later

**Comment by openoms** [comment]
Yes, just commenting out the `client.setCACert(test_root_ca);` lines still left the QRcode broken.
Doing the additional steps here: https://github.com/arcbtc/M5StackSats/issues/13#issue-500509357
made it work.
I am able to generate QR-s and pay to my node through LAN:  
`const char*  server = "192.168.1.xxx"; `  
 and dynamicDNS (with port forwarding) too:
`const char*  server = "xxx.ddns.net"; `

**Comment by Q8w3rgxr** [comment]
> Maybe try doing it without the cert
> comment out all the occurrences of
> `client.setCACert(test_root_ca);`
> to
> `//client.setCACert(test_root_ca);`

This did the trick. Thank you so much for helping me out! And thanks for your great piece of work! I`ll come back at you when i did some testing. (Actually i mistakenly opened that issue here but i was working on a M5Stack1.21 device, still it is fully operational now!)
