### ISSUE TITLE
Creating Invalid QR codes BTCPayServer version

### ISSUE THREAD

**Issue by mjlamb** [arcbtc/M5StackSats#27]
The BTCPayServer version is creating Invalid QR codes, these cannot be scanned.
If I manually create the qr from the lightning invoice string it will create fine in any online generator.
I think there is something wrong with M5.Lcd.qrcode(invoicePayReq, 45, 0, 240, 10);

**Comment by arcbtc** [comment]
If you can wait a few days, we're doing a major code refactor update, which should iron out any issues.
For now, if you want to diagnose further, try scanning the QR with a regular QR code scanner, and post the results

**Comment by normandmickey** [comment]
There needs to be a space in front of the legacy API key on line 19.  

String encodedApiKey = " VXJ..."

**Comment by ArbenKarb** [comment]
Same issue here. I compared the QR codes which are generated on the device to the ones generated in the RTL app (which are valid and work) by eye, and they do look different.

**Comment by ArbenKarb** [comment]
fixed. Tested with Zap Wallet.
